### ISSUE TITLE
add 30E/360 ISDA daycount method - refactor C code to python code

### ISSUE THREAD

**Issue by ulf1** [kmedian/yearfrac#1]
Todo 

1. refactor https://github.com/hcnn/d30360e/blob/master/d30360e.c to python code
2. add it as module `yearfrac/d30360e.py`

Optional because 

* unittest for the `test/...` folder
* demo notebook for the `example/...` folder
* add it to wrapper in `yearfrac/yearfrac.py`

Rewards

* the new feature will get an own `0.Y.0` version
* you are mentioned in the README.md

**Comment by vinschess** [comment]
Working on it.

**Comment by vinschess** [comment]
Created PR.

**Comment by ulf1** [comment]
Thank you
