### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by shingike** [kmedian/yearfrac#11]
Hi There,
I have been using this yearfrac tool to calc year fraction to simulate Excel's YEARFRAC function. I have recently encountered an issue as follows. Do you know what is causing this error?

d1 = datetime(2020,12,31)
d2 = datetime(2021,1,31)
x = yf.yearfrac(d1, d2, '30e360')

---------------------------------------------------------------------------
DeprecationWarning                        Traceback (most recent call last)
<ipython-input-81-699cf347df30> in <module>
      9 d2 = datetime(2021,1,31)
     10 d1, d2
---> 11 x = yf.yearfrac(d1, d2)
     12 # x

~\AppData\Local\Continuum\anaconda3\envs\flaskenv\lib\site-packages\yearfrac\yearfrac.py in yearfrac(d1, d2, method)
     57     yearfrac_func = __algorithm_mapper[
     58         (
---> 59             isinstance(d1, collections.Iterable),
     60             isinstance(d2, collections.Iterable)
     61         )

~\AppData\Local\Continuum\anaconda3\envs\flaskenv\lib\collections\__init__.py in __getattr__(name)
     50                       "of from 'collections.abc' is deprecated since Python 3.3,"
     51                       "and in 3.9 it will stop working",
---> 52                       DeprecationWarning, stacklevel=2)
     53         globals()[name] = obj
     54         return obj

DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
 
I can reproduce this error using Jupyter notebook/lab, but when I type the commands in python prompt, it works:
>>> import yearfrac as yf
>>> from datetime import datetime
>>> d1 = datetime(2020,12,31)
>>> d2 = datetime(2021,1,31)
>>> x = yf.yearfrac(d1, d2)
>>> x
0.0821917808219178
>>> x = yf.yearfrac(d1, d2, '30e360')
>>> x
0.08333333333333333

Thanks.

**Comment by shingike** [comment]
Apparently, it was caused by adding a warning filtering:
```
import warnings
warnings.filterwarnings('error')
```
As soon as I removed them, the issue is resolved.

**Comment by ulf1** [comment]
Hello @shingike 
Sorry for the late reply. I just notice your issue. 
Do you still have troubles? Should I take a look?

**Comment by ulf1** [comment]
Add a switch (see [here](https://github.com/tensorflow/tensorflow/pull/35998/commits/2fc25a1da1ad5d62f96a45542e6198b094e152c2))

```
...
# store the dtype
if sys.version_info[0] < 3:
    dtype_sequence = collections.Sequence  # py2
else:
      dtype_sequence = collections.abc.Sequence  # py3.9
...
# use it
if (isinstance(inputs, dtype_sequence):
    ...
```

However, the six package is said to be more appropriate https://six.readthedocs.io/

something like `six.moves.collections_abc`
