### ISSUE TITLE
cannot import name 'collections_abc' from 'six.moves'

### ISSUE THREAD

**Issue by Octanny** [kmedian/yearfrac#14]
I have encountered the following error while using another module (xlcalculator): cannot import name 'collections_abc' from 'six.moves'. The six version that I have installed for the root user is 1.15.0. Regarding the normal user, I have six v1.12.0 installed, and unfortunately, it can't be upgraded: "Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall"

The easy fix was to replace the line "from six.moves import collections_abc" with "from collections.abc import Iterable". I also replaced "collections_abc.Iterable" with "Iterable"

**Comment by ulf1** [comment]
~~@Octanny we can try to lower the requirement to `1.12.*`~~
Sorry version 1.12.* is too old.

It's good practice to use a virtual environment to sandbox your python stack. The advantage is that it would not interfere with your OS's python installation. You could run the following on you linux/mac command-line:

```bash
mypyvenv=/path/where/you/want/to/store/the/python/venv
python3 -m venv ${mypyvenv}
source "${mypyvenv}/bin/activate"
pip install xlcalculator==0.2.4.dev1
```

(Notes: You need to make sure that you have python3.7 or higher installed for `xlcalculator`, see https://github.com/bradbase/xlcalculator/blob/master/setup.py#L59)

**Comment by ulf1** [comment]
@Octanny 
I removed the `six` dependency

You need to install the version `yearfrac>=0.4.4`
https://pypi.org/manage/project/yearfrac/release/0.4.4/

The devs of [xlcalculator](https://github.com/bradbase/xlcalculator/blob/master/setup.py#L50) have not set the version. Thus, you might need to deinstall xlcalculator (and yearfrac) manually so that you get the latest version
