### ISSUE TITLE
add 30/365 daycount method -- refactor C function to python

### ISSUE THREAD

**Issue by ulf1** [kmedian/yearfrac#2]
Todo 

1. refactor https://github.com/hcnn/d30365/blob/master/d30365.c to python code
2. add it as module `yearfrac/d30365.py`

Optional 

* unittest for the `test/...` folder
* demo notebook for the `example/...` folder
* add it to wrapper in `yearfrac/yearfrac.py`

Rewards

* the new feature will get an own `0.Y.0` version
* you are mentioned in the README.md

**Comment by Argetan** [comment]
I'm on it!

**Comment by vinschess** [comment]
Created a PR.
