### ISSUE TITLE
Last day of the year not being counted

### ISSUE THREAD

**Issue by emiliobasualdo** [kmedian/yearfrac#20]
https://github.com/kmedian/yearfrac/blob/0969623073de10a3273caaf19cbbb91fec726de6/yearfrac/act_afb.py#L22

Hi there, great library!
I believe we found a small bug.
The last day of the year is not being taken into account in the subtraction because 12/31 is the begging of the day(00:00:00hs)

We believe the answer could be just adding 1 day
` diffa = date_to_jd(y1, 12, 31) - date_to_jd(y1, m1, d1) + 1 `

Please tell me what you think, best regards

**Comment by ulf1** [comment]
@emiliobasualdo Thank you for reporting the issue. I will take a look into it.

**Comment by ulf1** [comment]
Thanks @emiliobasualdo 
`pip install "yearfrac>=0.4.7"`
