### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by toy270** [kmedian/yearfrac#23]
Hi I have some issue to install yearfrac package as follows. Please guide us how to install successfully.

PS C:\Users\User\Downloads\yearfrac-0.4.7>  python setup.py install
Traceback (most recent call last):
  File "C:\Users\User\Downloads\yearfrac-0.4.7\setup.py", line 24, in <module>
    long_description=read('README.rst'),
  File "C:\Users\User\Downloads\yearfrac-0.4.7\setup.py", line 7, in read
    s = fp.read()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 488: illegal multibyte sequence

**Comment by ulf1** [comment]
Hello @toy270. Thank you for reporting this bug. 
I think @agroszer fixed this installation problem with the PR https://github.com/kmedian/yearfrac/pull/25

Could you try if it's working for you?
