### ISSUE TITLE
add a vectorized version of the yearfrac function

### ISSUE THREAD

**Issue by ulf1** [kmedian/yearfrac#3]
Current state

* `yearfrac.yearfrac(d1, d2)` expect two `datetime.dateime` objects `d1` and `d2`

Todo

* rewrite `yearfrac.yearfrac(d1, d2)` that it accept list, tuple, ndarray, panda cols, etc with date objects as `d1` or `d2`

Behavior

* Example 1: `d1` is a `datetime.datetime` object, `d2` is a `datetime.datetime` object, the return value is a floating point number
* Example 2: `d1` is a `datetime.datetime` object, `d2` is a list of `datetime.datetime` objects, the return value is a list of floating point numbers
* Example 3: `d1` is a list of `datetime.datetime` objects, `d2` is a list of `datetime.datetime` objects, the return value is a list of floating point numbers 

Links

* https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.vectorize.html

Optional 

* unittest for the `test/...` folder
* demo notebook for the `example/...` folder

Rewards

* the new feature will get an own `0.Y.0` version
* you are mentioned in the README.md as contributor

**Comment by fatkaratekid** [comment]
I'm on it. Optional parts will come later.

**Comment by jasjotiitr** [comment]
I'm also working on it.
